### ISSUE TITLE
dezelfde waarden

### ISSUE THREAD

**Issue by r20222** [RickVellingaa/object-detail-page-funda#13]
https://github.com/RickVellingaa/object-detail-page-funda/blob/2fba8a10ca49282450353a13c2cd5f563b3f11c3/styles/style.css#L128-L136

Deze twee hebben dezelfde waarde, je kan code besparen door een comma te te gebruiken:

```CSS
 .right-nav li a span, .hidden { 
     display: none; 
     visibility: hidden; 
 } 
```
